apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostpath-provisioner
  labels:
    k8s-app: hostpath-provisioner
  namespace: kube-system
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      k8s-app: hostpath-provisioner
  template:
    metadata:
      labels:
        k8s-app: hostpath-provisioner
    spec:
      containers:
        - name: hostpath-provisioner
          image: cdkbot/hostpath-provisioner:1.4.2
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: PV_DIR
              value: /var/snap/k8s/common/default-storage
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: hostpath
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: k8s.canonical.com/hostpath
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ssd-hostpath
provisioner: k8s.canonical.com/hostpath
reclaimPolicy: Delete
parameters:
  pvDir: /tmp/ssd-storage
volumeBindingMode: WaitForFirstConsumer
