apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ print (include "hostpath-provisioner.fullname" .) "-crb" }}
  labels:
    {{- include "hostpath-provisioner.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ print (include "hostpath-provisioner.fullname" .) "-cr" }}
subjects:
  - kind: ServiceAccount
    name: {{ print (include "hostpath-provisioner.fullname" .) "-sa" }}
    namespace: {{ .Release.Namespace }}
