apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ print (include "hostpath-provisioner.fullname" .) "-sa" }}
  labels:
    {{- include "hostpath-provisioner.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
